# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b88af1540ed10a865ce5dcfaef3d35d0f5f3cce64a0139733a68407f034dafc75d5bc128253034f44fbbee664ddcea595d318c7e35318b2f7061124fb331dd3

test:
  secret_key_base: be832d6462e48eb1a8c49f3ad47f8077c98d6b42f0125dd35bc4058ec59876108cc44ff6221ecdf5caf7b0852a5a0d8fff61b2050f4b0b546d465e731889710e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
